---
- hosts: all
  user: root
  become: yes
  tasks:
    - name: git install
      yum:
        name: git
        state: present
      tags: git
    - name: maven install
      yum:
        name: maven
        state: present
      tags: maven
    - name: directory create
      file:
        path: /opt/tomcat
        state: directory
      tags: directory
    - name: tomcat install
      unarchive:
        src: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.78/bin/apache-tomcat-9.0.78.tar.gz
        dest: /opt/tomcat
        remote_src: yes
      tags: tomcat
    - name: clone a github repositroy
      git:
        repo: https://github.com/kampemahender122/testing.git
        dest: /opt/mahender/mahi/
        clone: yes
      tags: clone
    - name: build maven
      command: mvn -f /opt/mahender/mahi/pom.xml clean package
      tags: build
    - name: deploy to tomcat
      shell: cp /opt/mahender/mahi/target/*.war /opt/tomcat/apache-tomcat-9.0.78/webapps/ROOT.war
      tags: deploy
    - name: run tomcat
      command: noup/opt/tomcat/apache-tomcat-9.0.78/bin startup.sh
      tags: run
