apiVersion: v1
kind: ReplicationController
metadata:
  name: babu
  labels:
    app: my-app
spec:
  replicas: 3
  template:
    metadata:
      name: pod
      labels:
        app: my-app
    spec:
      containers:
      - name: test
        image: kampemahender/casino
        ports:
        - containerPort: 8080
