---
- hosts: all
  user: root
  become: yes
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present
      tags: install
      notify:
        - start httpd
  handelers:
    - name: start httpd
      service:
        name: httpd
        state: started
      tags: start
    - name: deploy index.html
      copy:
        src: /root/index.html
        dest: /var/www/html/index.html
      tags: deploy
      
